<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="7" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-24T11:25:04 IST" name="Suite" finished-at="2025-01-24T11:25:14 IST" duration-ms="10669">
    <groups>
    </groups>
    <test started-at="2025-01-24T11:25:04 IST" name="Login" finished-at="2025-01-24T11:25:14 IST" duration-ms="10669">
      <class name="tests.TC_INVALID_PASSWORD">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.TC_INVALID_PASSWORD@3738449f]" started-at="2025-01-24T11:25:11 IST" name="setup" test-instance-name="Invalid password" finished-at="2025-01-24T11:25:12 IST" duration-ms="955" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="invalidCredentialsTest()[pri:0, instance:tests.TC_INVALID_PASSWORD@3738449f]" started-at="2025-01-24T11:25:12 IST" name="invalidCredentialsTest" description="Error message should be displayed when user enters invalid password" test-instance-name="Invalid password" finished-at="2025-01-24T11:25:13 IST" duration-ms="347" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidCredentialsTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.TC_INVALID_PASSWORD@3738449f]" started-at="2025-01-24T11:25:13 IST" name="tearDown" test-instance-name="Invalid password" finished-at="2025-01-24T11:25:13 IST" duration-ms="146" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.TC_INVALID_PASSWORD -->
      <class name="tests.TC_VALID_LOGIN">
        <test-method is-config="true" signature="globalSetup()[pri:0, instance:tests.TC_VALID_LOGIN@378542de]" started-at="2025-01-24T11:25:04 IST" name="globalSetup" test-instance-name="Login with valid credentials" finished-at="2025-01-24T11:25:04 IST" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- globalSetup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.TC_VALID_LOGIN@378542de]" started-at="2025-01-24T11:25:04 IST" name="setup" test-instance-name="Login with valid credentials" finished-at="2025-01-24T11:25:09 IST" duration-ms="5099" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginTest()[pri:0, instance:tests.TC_VALID_LOGIN@378542de]" started-at="2025-01-24T11:25:09 IST" name="loginTest" description="Testing the login Functionality" test-instance-name="Login with valid credentials" finished-at="2025-01-24T11:25:11 IST" duration-ms="2071" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at tests.TC_VALID_LOGIN.loginTest(TC_VALID_LOGIN.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.TC_VALID_LOGIN@378542de]" started-at="2025-01-24T11:25:11 IST" name="tearDown" test-instance-name="Login with valid credentials" finished-at="2025-01-24T11:25:11 IST" duration-ms="299" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="wrapUp(org.testng.ITestContext)[pri:0, instance:tests.TC_VALID_LOGIN@378542de]" started-at="2025-01-24T11:25:14 IST" name="wrapUp" test-instance-name="Login with valid credentials" finished-at="2025-01-24T11:25:14 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7b5b5bfe]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrapUp -->
      </class> <!-- tests.TC_VALID_LOGIN -->
      <class name="tests.TC_INVALID_USERNAME">
        <test-method is-config="true" signature="setup()[pri:0, instance:tests.TC_INVALID_USERNAME@69e1dd28]" started-at="2025-01-24T11:25:13 IST" name="setup" test-instance-name="Invalid Username" finished-at="2025-01-24T11:25:14 IST" duration-ms="926" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="invalidLoginTest()[pri:0, instance:tests.TC_INVALID_USERNAME@69e1dd28]" started-at="2025-01-24T11:25:14 IST" name="invalidLoginTest" description="Error message should be displayed when user tries to login with invalid username" test-instance-name="Invalid Username" finished-at="2025-01-24T11:25:14 IST" duration-ms="403" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.TC_INVALID_USERNAME@69e1dd28]" started-at="2025-01-24T11:25:14 IST" name="tearDown" test-instance-name="Invalid Username" finished-at="2025-01-24T11:25:14 IST" duration-ms="179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.TC_INVALID_USERNAME -->
    </test> <!-- Login -->
  </suite> <!-- Suite -->
</testng-results>
